services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.simple
    container_name: deer-flow-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./conf.yaml:/app/conf.yaml
    restart: unless-stopped
    networks:
      - deer-flow-network

networks:
  deer-flow-network:
    driver: bridge 